### ISSUE TITLE
Step3 running error

### ISSUE THREAD

**Issue by tyfann** [DreamerDeo/UniSAr_text2sql#1]
When I ran in step3: 
```shell
python step3_evaluate.py --constrain
```
I got error like this:
```shell
Traceback (most recent call last):
  File "step3_evaluate.py", line 334, in <module>
    predict_and_evaluate(model_path=args.model_path,
  File "step3_evaluate.py", line 196, in predict_and_evaluate
    data = predict_with_constrain(
  File "step3_evaluate.py", line 261, in predict_with_constrain
    model = GENRE.from_pretrained(model_path).eval()
  File "/data/data2/tyf/PycharmProject/UniSAr_text2sql/genre/fairseq_model.py", line 121, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/fairseq/hub_utils.py", line 70, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 224, in load_checkpoint_to_cpu
    state = torch.load(
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

And if I ran instruction: 
```shell
python step3_evaluate.py
```
I got error like this: 
```shell
Traceback (most recent call last):                                                                                                             
  File "step3_evaluate.py", line 334, in <module>                                                                                              
    predict_and_evaluate(model_path=args.model_path,                                                                                           
  File "step3_evaluate.py", line 209, in predict_and_evaluate                                                                                  
    correct_arr, correct_num, total = evaluate(data)                                                                                           
  File "step3_evaluate.py", line 190, in evaluate                                                                                              
    print("Correct/Total : {}/{}, {:.4f}".format(correct_num, total, correct_num / total))                                                     
ZeroDivisionError: division by zero
```

I don't know if there's something wrong in your code? Glad to hear your answer.

**Comment by DreamerDeo** [comment]
I think you should download model from huggingface use `git-lfs' as this [issue](https://github.com/YBIGTA/pytorch-hair-segmentation/issues/37).

**Comment by tyfann** [comment]
> I think you should download model from huggingface use `git-lfs' as this [issue](https://github.com/YBIGTA/pytorch-hair-segmentation/issues/37).

Fixed this problem, but I got another question like this:
```markdown
Traceback (most recent call last):
  File "step3_evaluate.py", line 334, in <module>
    predict_and_evaluate(model_path=args.model_path,
  File "step3_evaluate.py", line 196, in predict_and_evaluate
    data = predict_with_constrain(
  File "step3_evaluate.py", line 261, in predict_with_constrain
    model = GENRE.from_pretrained(model_path).eval()
  File "/data/data2/tyf/PycharmProject/UniSAr_text2sql/genre/fairseq_model.py", line 121, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/fairseq/hub_utils.py", line 70, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data/data2/conda_envs/text2sql/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 231, in load_checkpoint_to_cpu
    setattr(args, arg_name, arg_val)
AttributeError: 'NoneType' object has no attribute 'bpe'
```

I don't know if it was related to fairseq version? Can u show me your fairseq version?

**Comment by DreamerDeo** [comment]
You should install fairseq from this [source ](https://github.com/nicola-decao/fairseq/tree/fixing_prefix_allowed_tokens_fn).

> git clone git@github.com:nicola-decao/fairseq.git
cd fairseq
pip install --editable ./

**Comment by tyfann** [comment]
> Please install fairseq from this [source ](https://github.com/nicola-decao/fairseq/tree/fixing_prefix_allowed_tokens_fn).
> 
> > git clone [git@github.com](mailto:git@github.com):nicola-decao/fairseq.git
> > cd fairseq
> > pip install --editable ./
> 
> Since the constrained decoding is implemented base on [GENRE](https://github.com/facebookresearch/GENRE), we have to install the specific fairseq version as README suggested.

Thx! It does work.
